name: 03- Workflow runner
on: workflow_dispatch
jobs:
    ubuntu-echo:
     runs-on: ubuntu-latest
     steps:           
     - name: Show OS
       run: |
        echo "This job is running on ubuntu server"
        echo "Runner Os: $RUNNER_OS."