name: 05-01 Event type and Activity Types

on:
  workflow_dispatch:
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a pull request is opened or synchronized and base branch is main"
